### PR TITLE
fix: Support custom protocols in valueFiles

### LINKED ISSUE #29: [BUG] Support custom protocols in valueFiles
**Describe the bug**
It's not possible to use khelm with the helm secrets plugin. When providing a valuesFile in the format of `secrets://secret.yaml` a file not found error occurs.

**To Reproduce**
1. Install helm secrets plugin and create a sops encrypted valueFile
2. Execute `khelm template kube-vip --version=0.4.2 --repo=https://kube-vip.io/helm-charts --trust-any-repo -f=secrets://values.sops.yaml`
3. See error

```
Running khelm 2.0.0 (helm 3.8.0)
Using repository "https://kube-vip.io/helm-charts" (unauthenticated)
Using chart kube-vip from cache at /tmp/khelm/.cache/helm/repository/khelm/github.com/kube-vip/helm-charts/releases/download/kube-vip-0.4.2/kube-vip-0.4.2-d24805ca1360cdbb/kube-vip-0.4.2.tgz
Rendering chart kube-vip 0.4.2 with name "release-name" and namespace "default"
khelm: load values: open /tmp/khelm/secrets:/values.sops.yaml: no such file or directory
```
**Expected behavior**
khelm template should be able to render the manifests.

**khelm version:**
The khelm version you used.
Running khelm 2.0.0 (helm 3.8.0)

**Desktop (please complete the following information):**
 - OS: ArchLinux

**Additional context**
I've tracked this down to the calculation of the absolute path of the valueFiles. Essentially it doesn't take into account that a valid path could include a custom protocol and calculates the absPath on the whole string instead of just the path. This produces the exception seen above.

### PR DESCRIPTION
**Pull request by ndbrew**
Add logic to parse out a custom protocol from the valueFiles before calculating the absolute path.
If no protocol is found in the string, the same behavior as before is used.

This issue fixes #29

### CODE REVIEW

**Comment by ndbrew** [comment]
I'm not sure this can be properly unit tested without injecting a plugin that implements a custom protocol.
One method might be just to download the helm secrets plugin and override the HELM_PLUGIN env var during the build but that seemed a little messy.

Perhaps it's enough that existing tests don't break for now?
Ideally I'd like to see support for installing custom plugins via khelm as well, particularly for the kustomize_plugin use case.

**Comment by mgoltzsche** [comment]
@ndbrew thanks for providing the fix!

There should be a test to guarantee compatibility indeed.

> One method might be just to download the helm secrets plugin and override the HELM_PLUGIN env var during the build but that seemed a little messy.

Downloading the plugin temporarily into a sub directory of the `./build` directory and, when running the test, pointing Helm to it sounds good to me.

**Review by mgoltzsche — COMMENTED** [review]
Would you mind implementing the test?

**Review by mgoltzsche — APPROVED** [review]
Thanks @ndbrew! Awesome!

**Pull request merged**
